core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', include('apps.home.urls')),
    # course
    path('', include('apps.course.urls.subject_urls')),
    path('', include('apps.course.urls.course_urls')),
    path('', include('apps.course.urls.note_urls')),
    # finance
    path('', include('apps.finance.urls.category_urls')),
    path('', include('apps.finance.urls.account_urls')),
    path('', include('apps.finance.urls.transaction_urls')),
    path('', include('apps.finance.urls.transfer_urls')),
    path('', include('apps.finance.urls.cards_urls')),
    path('', include('apps.finance.urls.dashboard_urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/finance/models/category.py
from apps.finance.models import *


class Category(models.Model):
    TYPES_CHOICES = [
        ('receita', 'Receita'),
        ('despesa', 'Despesa'),
        ('investimento', 'Investimento'),
        ('transferencia', 'Transferência'),
    ]
    NATURES_CHOICES = [
        ('fixa', 'Fixa'),
        ('variavel', 'Variável'),
    ]
    PRIORITIES_CHOISES = [
        ('essencial', 'Essencial(50%)'),
        ('superflua', 'Superflua(30%)'),
        ('reserva', 'Reserva(20%)'),
    ]

    name = models.CharField(
        max_length=50,
        verbose_name='Nome'
    )
    parent = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='Categoria Pai',
        related_name='children'
    )
    order = models.IntegerField(
        verbose_name='Ordem de Apresentação'
    )
    category_type = models.CharField(
        max_length=15,
        choices=TYPES_CHOICES,
        default='despesa',
        verbose_name='Tipo de Categoria'
    )
    category_nature = models.CharField(
        max_length=15,
        choices=NATURES_CHOICES,
        default='fixa',
        verbose_name='Natureza da Categoria'
    )
    category_priority = models.CharField(
        max_length=15,
        choices=PRIORITIES_CHOISES,
        default='essencial',
        verbose_name='Prioridade(Método 50/30/20)'
    )
    planned_value = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default='0.00',
        verbose_name='Valor Planejado'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Usuário'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Criado em'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Alterado em'
    )
    active = models.BooleanField(
        'Categoria Ativa', default=True
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['name']
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

apps/finance/forms/account_forms.py
from django import forms

from apps.finance.models.account import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'type', 'opening_balance',  'logo', 'active']

        labels = {
            "name": ("Nome"),
            "type": ("Tipo de Conta"),
            "opening_balance": ("Saldo Inicial"),
            "logo": ("Logotipo"),
            "active": ("Conta Ativa")
        }

apps/finance/forms/category_forms.py
from django import forms

from apps.finance.models.category import Category


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['parent'].queryset = Category.objects.filter(
            parent__isnull=True)

    class Meta:
        model = Category
        fields = ['name', 'parent', 'order', 'category_type',
                  'category_nature', 'category_priority', 'active']

apps/finance/views/account_views.py
import sweetify

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView

from apps.finance.models.account import Account
from apps.finance.forms.account_forms import AccountForm


class AccountList(LoginRequiredMixin, ListView):
    model = Account
    context_object_name = 'accounts'
    template_name = 'account/account_list.html'
    paginate_by = 10

    def get_queryset(self):
        accounts = Account.objects.filter(user=self.request.user)
        query = self.request.GET.get('search')
        if query:
            accounts = accounts.filter(name__icontains=query)
        return accounts


class AccountCreate(LoginRequiredMixin, CreateView):
    model = Account
    template_name = 'account/account_form.html'
    form_class = AccountForm
    success_url = reverse_lazy('accounts')

    def form_valid(self, form):
        form.instance.user = self.request.user
        sweetify.toast(self.request, 'Conta incluida com sucesso',
                       icon="success", button='OK', timer=2000)
        return super(AccountCreate, self).form_valid(form)


class AccountUpdate(LoginRequiredMixin, UpdateView):
    model = Account
    template_name = 'account/account_form.html'
    form_class = AccountForm
    success_url = reverse_lazy('accounts')

    def form_valid(self, form):
        sweetify.toast(self.request, 'Conta alterada com sucesso',
                       icon="success", button='OK', timer=2000)

        return super(AccountUpdate, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(AccountUpdate, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class AccountDelete(LoginRequiredMixin, DeleteView):
    model = Account
    context_object_name = 'account'
    template_name = 'account/account_confirm_delete.html'
    success_url = reverse_lazy('accounts')

    def form_valid(self, form):
        sweetify.toast(self.request, 'Conta excluida com sucesso',
                       icon="error", button='OK', timer=2000)
        return super(AccountDelete, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(AccountDelete, self).get_queryset()
        return base_qs.filter(user=self.request.user)

apps/finance/views/card_views.py
import sweetify
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import redirect
from django.shortcuts import render

from apps.finance.models.category import Category
from apps.finance.models.account import Account
from apps.finance.models.transaction import Transaction
from apps.finance.utils.utils import cards_payment


@login_required
def CardList(request):
    template_name = 'cards/card_list.html'
    cards = []
    total_card = 0

    accounts = Account.objects.filter(
        user=request.user, type='CT').order_by('name')
    accounts_debit = Account.objects.filter(
        user=request.user, type='CC').order_by('name')
    categories = Category.objects.filter(
        user=request.user, category_type='transferencia')

    if request.method == 'GET':
        due_date = request.GET.get('due_date')
        account_id = request.GET.get('account')

        if due_date and account_id:
            cards = Transaction.objects.filter(
                user=request.user, account__id=account_id, due_date=due_date, type='D')
            total_card = cards.filter(is_paid=False).aggregate(
                Sum('transaction_value'))['transaction_value__sum'] or 0

        context = {
            'accounts': accounts,
            'cards': cards,
            'total_card': total_card,
            'accounts_debit': accounts_debit,
            'categories': categories,
        }
        return render(request, template_name, context)

    if request.method == 'POST':
        account_debit = request.POST.get('account_debit')
        category = request.POST.get('category')
        account_id = request.GET.get('account')
        due_date = request.GET.get('due_date')

        if account_debit and category:
            cards, total_cards = cards_payment(
                request.user,
                account_debit,
                category,
                account_id,
                due_date
            )

        sweetify.toast(request, 'Pagamento concluido com sucesso',
                       icon="success", button='OK', timer=2000)

        context = {
            'accounts': accounts,
            'cards': cards,
            'total_card': total_card,
            'accounts_debit': accounts_debit,
            'categories': categories,
        }
        return render(request, template_name, context)

apps/finance/views/category_views.py
import sweetify

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView

from apps.finance.models.category import Category
from apps.finance.forms.category_forms import CategoryForm
from apps.finance.utils.utils import transforms_categories


class CategoryList(LoginRequiredMixin, ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'category/category_list.html'
    paginate_by = 200

    def get_queryset(self):
        categories = Category.objects.filter(
            user=self.request.user, parent__isnull=True).order_by('order')
        return categories


class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    template_name = 'category/category_form.html'
    form_class = CategoryForm
    success_url = reverse_lazy('category-create')

    def form_valid(self, form):
        form.instance.user = self.request.user
        sweetify.toast(self.request, 'Categoria incluida com sucesso',
                       icon="success", button='OK', timer=2000)
        return super(CategoryCreate, self).form_valid(form)


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    template_name = 'category/category_form.html'
    form_class = CategoryForm
    success_url = reverse_lazy('categories')

    def form_valid(self, form):
        sweetify.toast(self.request, 'Categoria alterada com sucesso',
                       icon="success", button='OK', timer=2000)
        return super(CategoryUpdate, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(CategoryUpdate, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'category/category_confirm_delete.html'
    success_url = reverse_lazy('categories')

    def form_valid(self, form):
        sweetify.toast(self.request, 'Categoria excluida com sucesso',
                       icon="error", button='OK', timer=2000)
        return super(CategoryDelete, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(CategoryDelete, self).get_queryset()
        return base_qs.filter(user=self.request.user)


# def category_list_method(request):
#     categories = Category.objects.values_list(
#         'method', 'name').filter(user=request).order_by('method')

#     categories_method = {}
#     method_ant = 0
#     for method, name in categories:
#         if method != method_ant:
#             categories_method[method] = {}
#             method_ant == method
#         categories_method[method] = {'name': name, }

apps/finance/views/dashboard_views.py
import json
from datetime import date

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from apps.finance.utils import finance_metrics
from apps.finance.utils import finance_grafics


@login_required
def dashboard(request):
    today = date.today()

    labels_fix, data_fix, labels_var, data_var = finance_grafics.get_finance_expense_month(
        request, today.month, today.year)

    labels_year, data_expenses_year, data_incomes_year = finance_grafics.get_finance_incomes_expense_year(
        request, today.year)

    finance_balance = finance_metrics.get_finance_balance(
        request, today.month, today.year)

    finance_accounts_balance = finance_metrics.get_finance_accounts_balance(
        request)

    total_balance = finance_accounts_balance['balance_total']

    finance_pendents = finance_metrics.get_finance_pendents(
        total_balance, request)

    finance_method = finance_metrics.get_finance_method(request)

    context = {
        'finance_balance': finance_balance,
        'labels_fix': json.dumps(labels_fix),
        'data_fix': json.dumps(data_fix),
        'labels_var': json.dumps(labels_var),
        'data_var': json.dumps(data_var),
        'labels_year': json.dumps(labels_year),
        'data_expenses_year': json.dumps(data_expenses_year),
        'data_incomes_year': json.dumps(data_incomes_year),
        'finance_accounts_balance': finance_accounts_balance,
        'finance_pendents': finance_pendents,
        'finance_method': finance_method,
    }

    return render(request, 'dashboard/dashboard.html', context)

apps/finance/views/transaction_views.py
import sweetify
from datetime import date
from calendar import monthrange

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView

from apps.finance.forms.transaction_forms import TransactionForm
from apps.finance.models.account import Account
from apps.finance.models.transaction import Transaction


class TransactionList(LoginRequiredMixin, ListView):
    model = TransactionForm
    context_object_name = 'transactions'
    template_name = 'transaction/transaction_list.html'
    paginate_by = 100

    def get_queryset(self):
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        account = self.request.GET.get('account')

        if not start_date or not end_date:
            today = date.today()
            start_date = date(today.year, today.month, 1)
            end_date = start_date.replace(day=monthrange(
                start_date.year, start_date.month)[1])

        transactions = Transaction.objects\
            .filter(user=self.request.user, transaction_date__range=[start_date, end_date])\
            .order_by('-transaction_date', '-due_date', '-created_at')

        if account:
            transactions = transactions.filter(account__id=account)

        return transactions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["accounts"] = Account.objects.filter(user=self.request.user)
        return context


class TransactionCreate(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = 'transaction/transaction_form.html'
    form_class = TransactionForm
    success_url = reverse_lazy('transaction-create')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        form.instance.user = self.request.user
        sweetify.toast(self.request, 'Transação incluida com sucesso',
                       icon="success", button='OK', timer=2000)
        return super(TransactionCreate, self).form_valid(form)


class TransactionUpdate(LoginRequiredMixin, UpdateView):
    model = Transaction
    template_name = 'transaction/transaction_form.html'
    form_class = TransactionForm
    success_url = reverse_lazy('transactions')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        sweetify.toast(self.request, 'Transação alterada com sucesso',
                       icon="success", button='OK', timer=2000)
        return super(TransactionUpdate, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(TransactionUpdate, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class TransactionDelete(LoginRequiredMixin, DeleteView):
    model = Transaction
    context_object_name = 'transaction'
    template_name = 'transaction/transaction_confirm_delete.html'
    success_url = reverse_lazy('transactions')

    def form_valid(self, form):
        sweetify.toast(self.request, 'Transação excluida com sucesso',
                       icon="error", button='OK', timer=2000)
        return super(TransactionDelete, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(TransactionDelete, self).get_queryset()
        return base_qs.filter(user=self.request.user)

apps/finance/templates/category/category_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Exclusão de categoria{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}

<div class="d-flex align-items-center justify-content-between mt-4 border-bottom border-dark pb-2">
    <h1 class="h5">
        <i class="bi bi-trash me-2"></i>
        Exclusão de Categoria
    </h1>
    <a href="{% url 'categories' %}" class="btn btn-secondary shadow float-end">
        <i class="bi bi-card-list me-2"></i>
        Lista de Categorias
    </a>
</div>

<div class="d-flex align-items-center justify-content-center mt-5">
    <div class="col-md-10 col-lg-10">
        <div class="card shadow p-3 mb-2">
            <div class="card-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="h5 mt-3 mb-3">Tem certeza que deseja excluir a categoria ?</div>
                    <div class="row">
                        <div class="col-md-12">
                            <label class="form-label">Nome</label>
                            <input class="form-control fs-4 text-danger" type="text" value="{{ category.name }}"
                                disabled readonly>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger mt-5">
                        <i class="bi bi-trash me-2"></i>
                        Confirmar Exclusão
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/finance/templates/category/category_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% if category %}Alteração de {% else %}Nova {% endif %} Categoria{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}

<div class="d-flex align-items-center justify-content-between mt-4 border-bottom border-dark pb-2">
    <h1 class="h5">
        <i class="bi bi-file-plus"></i>
        {% if category %}Alteração de {% else %}Nova {% endif %} Categoria
    </h1>
    <a href="{% url 'categories' %}" class="btn btn-secondary shadow">
        <i class="bi bi-card-list me-2"></i>
        Lista de Categorias
    </a>
</div>

<div class="d-flex align-items-center justify-content-center mt-5">
    <div class="col-md-10 col-lg-10">
        <div class="card shadow">
            <div class="card-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                {{ form.active| as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                {{ form.name| as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                {{ form.parent| as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                {{ form.order| as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                {{ form.category_type| as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                {{ form.category_nature| as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                {{ form.category_priority| as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary shadow">
                        <i class="bi bi-check-lg"></i>
                        Salvar
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

apps/finance/templates/category/category_list.html
{% extends 'base.html'%}
{% load static %}

{% block title %}Lista de Categorias{% endblock title %}

{%block content%}

<div class="d-flex align-items-center justify-content-between mt-4 border-bottom border-dark pb-2">
    <h1 class="h5">
        <i class="bi bi-card-list me-2"></i>
        Categorias
    </h1>
    <a href="{% url 'category-create' %}" class="btn btn-secondary shadow">
        <i class="bi bi-plus-circle me-2"></i>
        Nova Categoria
    </a>
</div>

<div class="card shadow mt-2">
    <div class="card-body">
        {% if categories %}
        <div class="table-responsive">
            <table class="table table-sm table-hover" id="tabela-listar">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Tipo</th>
                        <th>Natureza</th>
                        <th>Prioridade</th>
                        <th class="table-col-acoes">Ação</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for category in categories %}
                    <tr>
                        <td class="text-primary fs-6 fw-bold">
                            {{ category.order }} - {{ category.name }}
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td class="table-col-acoes">
                            <a href="{% url 'category-update' category.id %}" class="btn btn-primary btn-sm me-2">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a href="{% url 'category-delete' category.id %}" class="btn btn-danger btn-sm">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                    {% if category.children.all %}
                    {% for child in category.children.all %}
                    <tr>
                        <td>{{ child.name }}</td>
                        <td>{{ child.get_category_type_display }}</td>
                        <td>{{ child.get_category_nature_display }}</td>
                        <td>{{ child.get_category_priority_display }}</td>
                        <td class="table-col-acoes">
                            <a href="{% url 'category-update' child.id %}" class="btn btn-primary btn-sm me-2">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a href="{% url 'category-delete' child.id %}" class="btn btn-danger btn-sm">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}